#!/bin/sh

# To generate PDFs that are somewhat OK you will need to have the Roboto and Roboto mono font families installed on your system
# https://fonts.google.com/specimen/Roboto
# https://fonts.google.com/specimen/Roboto+Mono

echo "-----Rebuilding documentation..."

echo "     >>> HTML (documentation/)"
echo "     > index.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/index.md -o documentation/index.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > about.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/about.md -o documentation/about.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > charset.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/charset.md -o documentation/charset.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > design.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/design.md -o documentation/design.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > developer.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/developer.md -o documentation/developer.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > faq.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/faq.md -o documentation/faq.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > features.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/features.md -o documentation/features.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > history.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/history.md -o documentation/history.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > allah.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/allah.md -o documentation/allah.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > resources.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/resources.md -o documentation/resources.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > sample.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/sample.md -o documentation/sample.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > support.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/support.md -o documentation/support.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > versions.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/versions.md -o documentation/versions.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > announcement.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/announcement.md -o documentation/announcement.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > special.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/special.md -o documentation/special.html --lua-filter=documentation/source/pandocfilters/filter-html.lua

echo "     >> developer documentation"

echo "     > dev01_intro.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/dev01_intro.md -o documentation/dev01_intro.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > dev02_glyphset.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/dev02_glyphset.md -o documentation/dev02_glyphset.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > dev03_interfaces.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/dev03_interfaces.md -o documentation/dev03_interfaces.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > dev03a_interfaceimages.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/dev03a_interfaceimages.md -o documentation/dev03a_interfaceimages.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > dev04_behteeth.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/dev04_behteeth.md -o documentation/dev04_behteeth.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > dev05_namingconv.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/dev05_namingconv.md -o documentation/dev05_namingconv.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > dev06_passes.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/dev06_passes.md -o documentation/dev06_passes.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > dev07_collisions.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/dev07_collisions.md -o documentation/dev07_collisions.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > dev08_kerning.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/dev08_kerning.md -o documentation/dev08_kerning.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > dev09_altkafs.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/dev09_altkafs.md -o documentation/dev09_altkafs.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > dev10_shortfinals.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/dev10_shortfinals.md -o documentation/dev10_shortfinals.html --lua-filter=documentation/source/pandocfilters/filter-html.lua

echo "     >>> PDF (documentation/pdf/)"
mkdir -p documentation/source/pdftemp

echo "     > index.html > index.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/index.md -o documentation/source/pdftemp/index.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/index.html documentation/pdf/index.pdf
echo "     > about.html > about.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/about.md -o documentation/source/pdftemp/about.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/about.html documentation/pdf/about.pdf
echo "     > charset.html > charset.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/charset.md -o documentation/source/pdftemp/charset.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/charset.html documentation/pdf/charset.pdf
echo "     > design.html > design.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/design.md -o documentation/source/pdftemp/design.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/design.html documentation/pdf/design.pdf
echo "     > developer.html > developer.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/developer.md -o documentation/source/pdftemp/developer.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/developer.html documentation/pdf/developer.pdf
echo "     > faq.html > faq.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/faq.md -o documentation/source/pdftemp/faq.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/faq.html documentation/pdf/faq.pdf
echo "     > history.html > history.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/history.md -o documentation/source/pdftemp/history.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/history.html documentation/pdf/history.pdf
echo "     > resources.html > resources.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/resources.md -o documentation/source/pdftemp/resources.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/resources.html documentation/pdf/resources.pdf
echo "     > support.html > support.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/support.md -o documentation/source/pdftemp/support.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/support.html documentation/pdf/support.pdf
echo "     > versions.html > versions.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/versions.md -o documentation/source/pdftemp/versions.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/versions.html documentation/pdf/versions.pdf
echo "     > announcement.html > announcement.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/announcement.md -o documentation/source/pdftemp/announcement.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/announcement.html documentation/pdf/announcement.pdf
echo "     > special.html > special.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/special.md -o documentation/source/pdftemp/special.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/special.html documentation/pdf/special.pdf


echo "     > dev01_intro.html > dev01_intro.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/dev01_intro.md -o documentation/source/pdftemp/dev01_intro.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/dev01_intro.html documentation/pdf/dev/dev01_intro.pdf
echo "     > dev02_glyphset.html > dev02_glyphset.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/dev02_glyphset.md -o documentation/source/pdftemp/dev02_glyphset.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/dev02_glyphset.html documentation/pdf/dev/dev02_glyphset.pdf
echo "     > dev03_interfaces.html > dev03_interfaces.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/dev03_interfaces.md -o documentation/source/pdftemp/dev03_interfaces.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/dev03_interfaces.html documentation/pdf/dev/dev03_interfaces.pdf
echo "     > dev03a_interfaceimages.html > dev03a_interfaceimages.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/dev03a_interfaceimages.md -o documentation/source/pdftemp/dev03a_interfaceimages.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/dev03a_interfaceimages.html documentation/pdf/dev/dev03a_interfaceimages.pdf
echo "     > dev04_behteeth.html > dev04_behteeth.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/dev04_behteeth.md -o documentation/source/pdftemp/dev04_behteeth.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/dev04_behteeth.html documentation/pdf/dev/dev04_behteeth.pdf
echo "     > dev05_namingconv.html > dev05_namingconv.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/dev05_namingconv.md -o documentation/source/pdftemp/dev05_namingconv.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/dev05_namingconv.html documentation/pdf/dev/dev05_namingconv.pdf
echo "     > dev06_passes.html > dev06_passes.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/dev06_passes.md -o documentation/source/pdftemp/dev06_passes.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/dev06_passes.html documentation/pdf/dev/dev06_passes.pdf
echo "     > dev07_collisions.html > dev07_collisions.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/dev07_collisions.md -o documentation/source/pdftemp/dev07_collisions.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/dev07_collisions.html documentation/pdf/dev/dev07_collisions.pdf
echo "     > dev08_kerning.html > dev08_kerning.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/dev08_kerning.md -o documentation/source/pdftemp/dev08_kerning.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/dev08_kerning.html documentation/pdf/dev/dev08_kerning.pdf
echo "     > dev09_altkafs.html > dev09_altkafs.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/dev09_altkafs.md -o documentation/source/pdftemp/dev09_altkafs.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/dev09_altkafs.html documentation/pdf/dev/dev09_altkafs.pdf
echo "     > dev10_shortfinals.html > dev10_shortfinals.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/dev10_shortfinals.md -o documentation/source/pdftemp/dev10_shortfinals.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/dev10_shortfinals.html documentation/pdf/dev/dev10_shortfinals.pdf

echo "     >>> PRODUCT SITE MARKDOWN (documentation/source/productsite/)"

echo "     > about.md"
python3 documentation/source/makepsmd.py documentation/source/about.md documentation/source/productsite/about.md -q
echo "     > charset.md"
python3 documentation/source/makepsmd.py documentation/source/charset.md documentation/source/productsite/charset.md -q
echo "     > design.md"
python3 documentation/source/makepsmd.py documentation/source/design.md documentation/source/productsite/design.md -q
echo "     > developer.md"
python3 documentation/source/makepsmd.py documentation/source/developer.md documentation/source/productsite/developer.md -q
echo "     > faq.md"
python3 documentation/source/makepsmd.py documentation/source/faq.md documentation/source/productsite/faq.md -q
echo "     > features.md"
python3 documentation/source/makepsmd.py documentation/source/features.md documentation/source/productsite/features.md -q
echo "     > history.md"
python3 documentation/source/makepsmd.py documentation/source/history.md documentation/source/productsite/history.md -q
echo "     > allah.md"
python3 documentation/source/makepsmd.py documentation/source/allah.md documentation/source/productsite/allah.md -q
echo "     > resources.md"
python3 documentation/source/makepsmd.py documentation/source/resources.md documentation/source/productsite/resources.md -q
echo "     > sample.md"
python3 documentation/source/makepsmd.py documentation/source/sample.md documentation/source/productsite/sample.md -q
echo "     > support.md"
python3 documentation/source/makepsmd.py documentation/source/support.md documentation/source/productsite/support.md -q
echo "     > versions.md"
python3 documentation/source/makepsmd.py documentation/source/versions.md documentation/source/productsite/versions.md -q
echo "     > announcement.md"
python3 documentation/source/makepsmd.py documentation/source/announcement.md documentation/source/productsite/announcement.md -q
echo "     > special.md"
python3 documentation/source/makepsmd.py documentation/source/special.md documentation/source/productsite/special.md -q
echo "     Markdown source for other pages is in separate repo"



echo "-----Completed!"
