#!/bin/sh
# Update UFO after any edits other than with FontForge and prior to commit

echo
echo "Normalising UFO..."
psfnormalize -p checkfix=fix source/AwamiNastaliq-Regular.ufo

echo
echo "Setting glyph order..."
psfsetglyphorder -p checkfix=none -i source/glyphorder.txt source/AwamiNastaliq-Regular.ufo

