#!/bin/sh
# Update UFO after editing with FontForge and prior to commit

echo
echo "Fixing FontForge debris and normalizing UFOs..."
psffixffglifs -p checkfix=fix source/masters/AwamiNastaliq-Regular.ufo

echo
echo "Setting glyph order..."
psfsetglyphorder -p checkfix=none -i source/glyphorder.txt source/masters/AwamiNastaliq-Regular.ufo
