#!/bin/sh
# script to convert UFOs to glyphs file for editing

# Create UFO from Glyphs file
echo
echo "Converting UFO3 to .glyphs..."
psfufo2glyphs source/awami.designspace source/masters/AwamiNastaliq.glyphs -l source/logs/ufo2g.log
