#!/bin/sh
# script to convert UFOs to glyphs file for editing

GLYPHS_FILE_STEM="source/masters/AwamiNastaliq"
GLYPHS_FILE="$GLYPHS_FILE_STEM.glyphs"
GLYPHS_FILE_COPY="$GLYPHS_FILE_STEM-copy.glyphs"

# Make backup of .glyphs file - now a standard part of psfufo2glyphs
#echo "Making backup of .glyphs file..."
#cp $GLYPHS_FILE $GLYPHS_FILE_COPY

# Create UFO from Glyphs file
echo
echo "Converting UFO3 to .glyphs..."
psfufo2glyphs source/awami.designspace $GLYPHS_FILE -l source/logs/ufo2g.log
