#!/bin/sh

# generate Debg table
export FONTTOOLS_LOOKUP_DEBUGGING=1

cd tools/bin

./mkglyphbounds -o ../../source/opentype/autoKernMetrics.feax ../../source/masters/AwamiNastaliq-Regular.ufo

cd ../..

smith distclean
smith configure
smith build -v --psnames
#smith test
#smith sile
#smith pdfs
