#!/bin/sh

# generate Debg table
export FONTTOOLS_LOOKUP_DEBUGGING=1

smith distclean
smith configure
smith build -v --psnames #--qd

#echo NOTE: Ignore warning about mainQD

#smith test
#smith sile
#smith pdfs
