#!/usr/bin/python3

# Outputs a set of rules to perform bariyeh tail kerning.

# Run this script from the tools/scripts directory where the file is located:
#		python3 genBariyehKernRules.py

# The resulting rules look like:
#		sub @KNarrowIni' lookup _ByKern2350		nlqBariyehFin;
#		sub @KWideIni' lookup _ByKern850		@KMediumMed  nlqBariyehFin;
# etc.

# When run in "pos" mode, the output assumes a set of kerning lookups such as:
#		lookup _ByKern150 { pos @AllBases 150; } _ByKern150;
# etc.
#
# When run in "sub" mode, it assumes a set of lookups such as:
#		lookup _ByKern150 { sub @Initials by kw150 @Initials } _ByKern150;
# etc.

# This version of the script assumes 5 width classes. At this point that number seems
# like the best bang for buck. When I tried 6 classes it didn't seem to improve the 
# behavior much if at all.

mode = "sub"
#mode = "pos"

import sys

def ExpandSeq(mode, seqSoFar, slotTotal, depth):
	#print("ExpandSeq" + " " + str(slotTotal) + " depth=" + str(depth))
	#print(seqSoFar)
	
	if len(seqSoFar) >= slotTotal:
		needed = OutputRuleIfNeeded(mode, seqSoFar)
		return needed
	else:
		for wc in range(numClasses):
			nextSeq = seqSoFar.copy()
			nextSeq.append(wc)
			#print("nextSeq=")
			#print(nextSeq)
			needed = ExpandSeq(mode, nextSeq, slotTotal, depth+1)
			#print("return to ExpandSeq depth " + str(depth))
			# if not needed:
			# 	return True		# nothing more is needed for this sequence, but something might be needed for another
		return True
		
# end of ExpandSeq

def OutputRuleIfNeeded(mode, seq):
	print("OutputRuleIfNeeded")
	print(seq)
	totalWidth = 0
	
	if seq[0] == 0:
		return True;	# don't bother with KZeroIni, since the class is empty
		
	if TooManyZeroSlots(seq):
		return True;
		
	for w in seq:
		totalWidth += TypicalWidth(w)
	#print("totalWidth=" + str(totalWidth))
	if totalWidth < BariyehWidth:
		kernValue = BariyehWidth - totalWidth
		OutputRule(mode, seq, kernValue)
		#OutputTextString(seq)
		#print("return True")
		return True
	else:
		#print("return False")
		# Prevent kerning under the first char, because there is a good chance that the
		# bariyeh is underneath it.
		if totalWidth - BariyehWidth < 1000:
			OutputRule(mode, seq, "prevent")

		return False

# end of OutputRuleIfNeeded

def OutputRule(mode, seq, kernValue):
	outputStr = mode + " ";
	first = True
	#suffix = "Ini  "  # for inserting after previous final
	suffix = "Ini"
	for slot in seq:
		c = ClassName(slot) + suffix
		outputStr += "@" + c
		if first:
			outputStr  += "' lookup "
			#outputStr += "@IsoFin' lookup "  # for inserting after previous final
			if kernValue == "prevent":
				outputStr += "_PreventKernUnder\t"
			else:
				outputStr += "_ByKern" + str(kernValue) + "\t\t"
		#outputStr += "@" + c  # for inserting after previous final

		first = False
		suffix = "Med  "
	outputStr += "nlqBariyehFin;"
		
	print(outputStr, file=fout)
	
# end of OutputRule

def TooManyZeroSlots(seq):
	# Zero-width glyphs are relatively rare (mainly medial jeems), so if there are 
	# a lot of them in the rule, don't bother.
	zeros = 0
	for s in seq:
		if s == 0:
			zeros += 1
			if zeros > 3:
				return True
	return False

def TypicalWidth(w):
	# The numbers below are based on the values used in genKernWidthClasses.py.
	if w == 0:		# zero
		return 50
	elif w == 1:	# narrow
		return 350
	elif w == 2:	# medium
		return 700
	elif w == 3:	# wide
		return 1150
	else:
		return 1500		# extra wide
		
def ClassName(w):
	if w == 0:		# zero
		return "KZero"
	elif w == 1:	# narrow
		return "KNarrow"
	elif w == 2:	# medium
		return "KMedium"
	elif w == 3:	# wide
		return "KWide"
	else:					# extra-wide
		return "KExtra"
	

# -----------------------------
# These are versions of the functions that are used for 6 classes.

def TypicalWidth_6(w):
	# The numbers below are based on the values used in genKernWidthClasses.py.
	if w == 0:			# zero
		return 0
	elif w == 1:		# narrow
		return 300
	elif w == 2:		# medium
		return 650
	elif w == 3:		# wide
		return 1000
	elif w == 4:		# extra wide
		return 1300
	else:						# huge
		return 1700
		
def ClassName_6(w):
	if w == 0:		# zero
		return "KZero"
	elif w == 1:	# narrow
		return "KNarrow"
	elif w == 2:	# medium
		return "KMedium"
	elif w == 3:	# wide
		return "KWide"
	elif w == 4:	# extra-wide
		return "KExtra"
	else:					# huge
		return "KHuge"

# -----------------------------
# Main routine

BariyehWidth = 2700
outfile = "../../source/opentype/bariyehKernRules.feax"
fout = open(outfile, 'w');

print("mode = " + mode)

print("# This file was generated by the genBariyehKernRules.py script.\n", file=fout)

print("#lookup Kern4BariyehTail:", file=fout)	# the lookup definition is assumed to be in the main file
#print("#lookup Kern4BariyehTail {", file=fout)
#print("\tlookupflag IgnoreMarks;", file=fout)

# Must match the number of classes generated by the genKernWidthClasses.py script:
numClasses = 5

slotCounts = [1, 2, 3, 4, 5]

for slots in slotCounts:
	stxt = " SLOT" if slots == 1 else " SLOTS"
	print("\n# RULES WITH " + str(slots) + stxt + "\n", file=fout)
	ExpandSeq(mode, [], slots, 0);

#print("\n} Kern4BariyehTail;", file=fout)

fout.close()

print("Written to '" + outfile + "'")