#!/bin/sh

# Generate improved octaboxes and store in .json format
echo "AwamiNastaliq-Regular..."
octalap -j 0 -q -o ../source/graphite/octabox_AwamiNastaliq-Regular.json   ../results/AwamiNastaliq-Regular.ttf

echo "AwamiNastaliq-Medium..."
octalap -j 0 -q -o ../source/graphite/octabox_AwamiNastaliq-Medium.json    ../results/AwamiNastaliq-Medium.ttf

echo "AwamiNastaliq-SemiBold..."
octalap -j 0 -q -o ../source/graphite/octabox_AwamiNastaliq-SemiBold.json  ../results/AwamiNastaliq-SemiBold.ttf

echo "AwamiNastaliq-Bold..."
octalap -j 0 -q -o ../source/graphite/octabox_AwamiNastaliq-Bold.json      ../results/AwamiNastaliq-Bold.ttf

echo "AwamiNastaliq-ExtraBold..."
octalap -j 0 -q -o ../source/graphite/octabox_AwamiNastaliq-ExtraBold.json ../results/AwamiNastaliq-ExtraBold.ttf

echo "Done"
